targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          - lib/**/*.dart
      json_serializable:
        enabled: true
        generate_for:
          - lib/**/*.dart
      riverpod_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart

