// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt5l8sYxVENOAhKTIg6UuieXIff0W78AA',
    appId: '1:178549241698:web:d572f6a95fbdd220d11e3b',
    messagingSenderId: '178549241698',
    projectId: 'jouleport-c0a88',
    authDomain: 'jouleport-c0a88.firebaseapp.com',
    storageBucket: 'jouleport-c0a88.firebasestorage.app',
    measurementId: 'G-E8VT7CMSCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDth5Ae8NCJlYPTrRlAeF4EHesx5O0NmTo',
    appId: '1:178549241698:android:4dc8a7e5f9673c08d11e3b',
    messagingSenderId: '178549241698',
    projectId: 'jouleport-c0a88',
    storageBucket: 'jouleport-c0a88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQgSKtjQ-zs4wArb5dygzU8KHO0yNuBE',
    appId: '1:178549241698:ios:00158655c403c3f4d11e3b',
    messagingSenderId: '178549241698',
    projectId: 'jouleport-c0a88',
    storageBucket: 'jouleport-c0a88.firebasestorage.app',
    iosClientId: '178549241698-af6god8pdjtou5b6m04ntop2f97hthqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.evChargingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQgSKtjQ-zs4wArb5dygzU8KHO0yNuBE',
    appId: '1:178549241698:ios:00158655c403c3f4d11e3b',
    messagingSenderId: '178549241698',
    projectId: 'jouleport-c0a88',
    storageBucket: 'jouleport-c0a88.firebasestorage.app',
    iosClientId: '178549241698-af6god8pdjtou5b6m04ntop2f97hthqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.evChargingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt5l8sYxVENOAhKTIg6UuieXIff0W78AA',
    appId: '1:178549241698:web:13468d1310721864d11e3b',
    messagingSenderId: '178549241698',
    projectId: 'jouleport-c0a88',
    authDomain: 'jouleport-c0a88.firebaseapp.com',
    storageBucket: 'jouleport-c0a88.firebasestorage.app',
    measurementId: 'G-R82GZWFKDJ',
  );

}